/*
 *   Copyright 2016-2022 Oleksii V. KHALIKOV
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

/*
 * Client Portal Web API
 * Client Poral Web API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ua.com.gfalcon.financier.ibkr.client.okhttp.api;

import java.util.List;

import org.junit.Ignore;
import org.junit.Test;

import ua.com.gfalcon.financier.ibkr.model.Body;
import ua.com.gfalcon.financier.ibkr.model.Notifications;

/**
 * API tests for FyiApi
 */
@Ignore
public class FyiApiTest {

    private final FyiApi api = new FyiApi();


    /**
     * Delete a device
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void fyiDeliveryoptionsDeviceIdDeleteTest() throws Exception {
        String deviceId = null;
        Object response = api.fyiDeliveryoptionsDeviceIdDelete(deviceId);

        // TODO: test validations
    }

    /**
     * Enable/Disable device option
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void fyiDeliveryoptionsDevicePostTest() throws Exception {
        Body body = null;
        Object response = api.fyiDeliveryoptionsDevicePost(body);

        // TODO: test validations
    }

    /**
     * Enable/Disable email option
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void fyiDeliveryoptionsEmailPutTest() throws Exception {
        String enabled = null;
        Object response = api.fyiDeliveryoptionsEmailPut(enabled);

        // TODO: test validations
    }

    /**
     * Get delivery options
     * <p>
     * options for sending fyis to email and other devices
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void fyiDeliveryoptionsGetTest() throws Exception {
        Object response = api.fyiDeliveryoptionsGet();

        // TODO: test validations
    }

    /**
     * Get disclaimer for a certain kind of fyi
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void fyiDisclaimerTypecodeGetTest() throws Exception {
        String typecode = null;
        Object response = api.fyiDisclaimerTypecodeGet(typecode);

        // TODO: test validations
    }

    /**
     * Mark disclaimer read
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void fyiDisclaimerTypecodePutTest() throws Exception {
        String typecode = null;
        Object response = api.fyiDisclaimerTypecodePut(typecode);

        // TODO: test validations
    }

    /**
     * Get a list of notifications
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void fyiNotificationsGetTest() throws Exception {
        String max = null;
        String exclude = null;
        String include = null;
        Notifications response = api.fyiNotificationsGet(max, exclude, include);

        // TODO: test validations
    }

    /**
     * Get more notifications based on a certain one
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void fyiNotificationsMoreGetTest() throws Exception {
        String id = null;
        Notifications response = api.fyiNotificationsMoreGet(id);

        // TODO: test validations
    }

    /**
     * Get a list of notifications
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void fyiNotificationsNotificationIdPutTest() throws Exception {
        String notificationId = null;
        Object response = api.fyiNotificationsNotificationIdPut(notificationId);

        // TODO: test validations
    }

    /**
     * Get a list of subscriptions
     * <p>
     * Return the current choices of subscriptions, we can toggle the option
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void fyiSettingsGetTest() throws Exception {
        List<Object> response = api.fyiSettingsGet();

        // TODO: test validations
    }

    /**
     * Enable/Disable certain subscription
     * <p>
     * Configure which typecode you would like to enable/disable.
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void fyiSettingsTypecodePostTest() throws Exception {
        String typecode = null;
        Body body = null;
        Object response = api.fyiSettingsTypecodePost(typecode, body);

        // TODO: test validations
    }

    /**
     * Get unread number of fyis. The HTTP method POST is also supported.
     * <p>
     * Returns the total number of unread fyis
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void fyiUnreadnumberGetTest() throws Exception {
        Object response = api.fyiUnreadnumberGet();

        // TODO: test validations
    }

}
