/*
 *   Copyright 2016-2022 Oleksii V. KHALIKOV
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

/*
 * Client Portal Web API
 * Client Poral Web API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ua.com.gfalcon.financier.ibkr.client.okhttp.api;

import org.junit.Ignore;
import org.junit.Test;

import ua.com.gfalcon.financier.ibkr.model.HistoryResult;

/**
 * API tests for MarketDataBetaApi
 */
@Ignore
public class MarketDataBetaApiTest {

    private final MarketDataBetaApi api = new MarketDataBetaApi();


    /**
     * Market Data History
     * <p>
     * Using direct to market data farm connection, will provide a list of historical market data for a given conid
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void hmdsHistoryGetTest() throws Exception {
        Integer conid = null;
        String period = null;
        String bar = null;
        Boolean outsideRth = null;
        HistoryResult response = api.hmdsHistoryGet(conid, period, bar, outsideRth);

        // TODO: test validations
    }

}
