/*
 *   Copyright 2016-2022 Oleksii V. KHALIKOV
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

/*
 * Client Portal Web API
 * Client Poral Web API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ua.com.gfalcon.financier.ibkr.client.okhttp.api;

import org.junit.Ignore;
import org.junit.Test;

import ua.com.gfalcon.financier.ibkr.model.Body;
import ua.com.gfalcon.financier.ibkr.model.Performance;
import ua.com.gfalcon.financier.ibkr.model.Summary;
import ua.com.gfalcon.financier.ibkr.model.Transactions;

/**
 * API tests for PortfolioAnalystApi
 */
@Ignore
public class PortfolioAnalystApiTest {

    private final PortfolioAnalystApi api = new PortfolioAnalystApi();


    /**
     * Account Performance
     * <p>
     * Returns the performance (MTM) for the given accounts, if more than one account is passed, the result is
     * consolidated.
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void paPerformancePostTest() throws Exception {
        Body body = null;
        Performance response = api.paPerformancePost(body);

        // TODO: test validations
    }

    /**
     * Account Balance&#39;s Summary
     * <p>
     * Returns a summary of all account balances for the given accounts, if more than one account is passed, the result
     * is consolidated.
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void paSummaryPostTest() throws Exception {
        Body body = null;
        Summary response = api.paSummaryPost(body);

        // TODO: test validations
    }

    /**
     * Position&#39;s Transaction History
     * <p>
     * transaction history for a given number of conids and accounts. Types of transactions include dividend payments,
     * buy and sell transactions, transfers.
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void paTransactionsPostTest() throws Exception {
        Body body = null;
        Transactions response = api.paTransactionsPost(body);

        // TODO: test validations
    }

}
