/*
 *   Copyright 2016-2022 Oleksii V. KHALIKOV
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

/**
 * Client Portal Web API
 * Client Poral Web API
 * <p>
 * OpenAPI spec version: 1.0.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package ua.com.gfalcon.financier.ibkr.client.jaxrs.api;

import java.util.ArrayList;
import java.util.List;

import org.apache.cxf.jaxrs.client.ClientConfiguration;
import org.apache.cxf.jaxrs.client.JAXRSClientFactory;
import org.apache.cxf.jaxrs.client.WebClient;
import org.junit.Before;
import org.junit.Test;

import com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider;

import ua.com.gfalcon.financier.ibkr.model.Body;


/**
 * Client Portal Web API
 *
 * <p>Client Poral Web API
 *
 * API tests for FyiApi 
 */
public class FyiApiTest {


    private FyiApi api;

    /**
     * Delete a device
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fyiDeliveryoptionsDeviceIdDeleteTest() {
        String deviceId = null;
        //Object response = api.fyiDeliveryoptionsDeviceIdDelete(deviceId);
        //assertNotNull(response);
        // TODO: test validations


    }

    /**
     * Enable/Disable device option
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fyiDeliveryoptionsDevicePostTest() {
        Body body = null;
        //Object response = api.fyiDeliveryoptionsDevicePost(body);
        //assertNotNull(response);
        // TODO: test validations


    }

    /**
     * Enable/Disable email option
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fyiDeliveryoptionsEmailPutTest() {
        String enabled = null;
        //Object response = api.fyiDeliveryoptionsEmailPut(enabled);
        //assertNotNull(response);
        // TODO: test validations


    }

    /**
     * Get delivery options
     *
     * options for sending fyis to email and other devices
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fyiDeliveryoptionsGetTest() {
        //Object response = api.fyiDeliveryoptionsGet();
        //assertNotNull(response);
        // TODO: test validations


    }

    /**
     * Get disclaimer for a certain kind of fyi
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fyiDisclaimerTypecodeGetTest() {
        String typecode = null;
        //Object response = api.fyiDisclaimerTypecodeGet(typecode);
        //assertNotNull(response);
        // TODO: test validations


    }

    /**
     * Mark disclaimer read
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fyiDisclaimerTypecodePutTest() {
        String typecode = null;
        //Object response = api.fyiDisclaimerTypecodePut(typecode);
        //assertNotNull(response);
        // TODO: test validations


    }

    /**
     * Get a list of notifications
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fyiNotificationsGetTest() {
        String max = null;
        String exclude = null;
        String include = null;
        //Notifications response = api.fyiNotificationsGet(max, exclude, include);
        //assertNotNull(response);
        // TODO: test validations


    }

    /**
     * Get more notifications based on a certain one
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fyiNotificationsMoreGetTest() {
        String id = null;
        //Notifications response = api.fyiNotificationsMoreGet(id);
        //assertNotNull(response);
        // TODO: test validations


    }

    /**
     * Get a list of notifications
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fyiNotificationsNotificationIdPutTest() {
        String notificationId = null;
        //Object response = api.fyiNotificationsNotificationIdPut(notificationId);
        //assertNotNull(response);
        // TODO: test validations


    }

    /**
     * Get a list of subscriptions
     *
     * Return the current choices of subscriptions, we can toggle the option
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fyiSettingsGetTest() {
        //List<Object> response = api.fyiSettingsGet();
        //assertNotNull(response);
        // TODO: test validations


    }

    /**
     * Enable/Disable certain subscription
     *
     * Configure which typecode you would like to enable/disable.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fyiSettingsTypecodePostTest() {
        String typecode = null;
        Body body = null;
        //Object response = api.fyiSettingsTypecodePost(typecode, body);
        //assertNotNull(response);
        // TODO: test validations


    }

    /**
     * Get unread number of fyis. The HTTP method POST is also supported.
     *
     * Returns the total number of unread fyis
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fyiUnreadnumberGetTest() {
        //Object response = api.fyiUnreadnumberGet();
        //assertNotNull(response);
        // TODO: test validations


    }

    @Before
    public void setup() {
        JacksonJsonProvider provider = new JacksonJsonProvider();
        List providers = new ArrayList();
        providers.add(provider);

        api = JAXRSClientFactory.create("https://localhost:5000/v1/api", FyiApi.class, providers);
        org.apache.cxf.jaxrs.client.Client client = WebClient.client(api);

        ClientConfiguration config = WebClient.getConfig(client);
    }

}
