/*
 *   Copyright 2016-2022 Oleksii V. KHALIKOV
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

/**
 * Client Portal Web API
 * Client Poral Web API
 * <p>
 * OpenAPI spec version: 1.0.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package ua.com.gfalcon.financier.ibkr.client.jaxrs.api;

import java.util.ArrayList;
import java.util.List;

import org.apache.cxf.jaxrs.client.ClientConfiguration;
import org.apache.cxf.jaxrs.client.JAXRSClientFactory;
import org.apache.cxf.jaxrs.client.WebClient;
import org.junit.Before;
import org.junit.Test;

import com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider;

import ua.com.gfalcon.financier.ibkr.model.Body;
import ua.com.gfalcon.financier.ibkr.model.ScannerParams;


/**
 * Client Portal Web API
 *
 * <p>Client Poral Web API
 *
 * API tests for ScannerApi 
 */
public class ScannerApiTest {


    private ScannerApi api;

    /**
     * Run Scanner (Beta)
     *
     * Using a direct connection to the market data farm, will provide results to the requested scanner.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void hmdsScannerPostTest() {
        Body body = null;
        //ScannerResult response = api.hmdsScannerPost(body);
        //assertNotNull(response);
        // TODO: test validations


    }

    /**
     * Scanner Parameters
     *
     * Returns an object contains four lists contain all parameters for scanners
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void iserverScannerParamsGetTest() {
        //Object response = api.iserverScannerParamsGet();
        //assertNotNull(response);
        // TODO: test validations


    }

    /**
     * run scanner to get a list of contracts
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void iserverScannerRunPostTest() {
        ScannerParams body = null;
        //List<Object> response = api.iserverScannerRunPost(body);
        //assertNotNull(response);
        // TODO: test validations


    }

    @Before
    public void setup() {
        JacksonJsonProvider provider = new JacksonJsonProvider();
        List providers = new ArrayList();
        providers.add(provider);

        api = JAXRSClientFactory.create("https://localhost:5000/v1/api", ScannerApi.class, providers);
        org.apache.cxf.jaxrs.client.Client client = WebClient.client(api);

        ClientConfiguration config = WebClient.getConfig(client);
    }

}
