/*
 *   Copyright 2016-2022 Oleksii V. KHALIKOV
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

/**
 * Client Portal Web API
 * Client Poral Web API
 * <p>
 * OpenAPI spec version: 1.0.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package ua.com.gfalcon.financier.ibkr.client.jaxrs.api;

import java.util.ArrayList;
import java.util.List;

import org.apache.cxf.jaxrs.client.ClientConfiguration;
import org.apache.cxf.jaxrs.client.JAXRSClientFactory;
import org.apache.cxf.jaxrs.client.WebClient;
import org.junit.Before;
import org.junit.Test;

import com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider;


/**
 * Client Portal Web API
 *
 * <p>Client Poral Web API
 *
 * API tests for SessionApi 
 */
public class SessionApiTest {


    private SessionApi api;

    /**
     * Authentication Status
     *
     * Current Authentication status to the Brokerage system. Market Data and Trading is not possible if not authenticated, e.g. authenticated shows false
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void iserverAuthStatusPostTest() {
        //AuthStatus response = api.iserverAuthStatusPost();
        //assertNotNull(response);
        // TODO: test validations


    }

    /**
     * Tries to re-authenticate to Brokerage
     *
     * When using the CP Gateway, this endpoint provides a way to reauthenticate to the Brokerage system as long as there is a valid SSO session, see /sso/validate.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void iserverReauthenticatePostTest() {
        //AuthStatus response = api.iserverReauthenticatePost();
        //assertNotNull(response);
        // TODO: test validations


    }

    /**
     * Ends the current session
     *
     * Logs the user out of the gateway session. Any further activity requires re-authentication.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void logoutPostTest() {
        //Object response = api.logoutPost();
        //assertNotNull(response);
        // TODO: test validations


    }

    @Before
    public void setup() {
        JacksonJsonProvider provider = new JacksonJsonProvider();
        List providers = new ArrayList();
        providers.add(provider);

        api = JAXRSClientFactory.create("https://localhost:5000/v1/api", SessionApi.class, providers);
        org.apache.cxf.jaxrs.client.Client client = WebClient.client(api);

        ClientConfiguration config = WebClient.getConfig(client);
    }

    /**
     * Validate SSO
     *
     * Validates the current session for the SSO user
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void ssoValidateGetTest() {
        //Object response = api.ssoValidateGet();
        //assertNotNull(response);
        // TODO: test validations


    }

    /**
     * Ping the server to keep the session open
     *
     * If the gateway has not received any requests for several minutes an open session will automatically timeout. The tickle endpoint pings the server to prevent the session from ending.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void ticklePostTest() {
        //api.ticklePost();

        // TODO: test validations


    }

}
